
services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus_cont
    restart: always
    ports:
      - '9090:9090'
    volumes:
      - 'prometheus_data:/prometheus'
    networks:
      - net01

  grafana:
    image: grafana/grafana
    container_name: grafana_cont
    restart: always
    environment:
      - GF_SERVER_ROOT_URL=${GF_SERVER_ROOT_URL}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
    ports:
      - '3000:3000'
    volumes:
      - 'grafana_data:/var/lib/grafana'
    networks:
      - net01

networks:
 net01:
   driver: bridge


volumes:
  grafana_data:
  prometheus_data:


